import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";

/**
 * ▸ THE ONLY PLACE THE DOMAIN IS DEFINED. ◂
 *
 * Change this one line and everything follows: canonical URLs, Open Graph
 * tags, sitemap.xml, RSS links, and the CNAME file GitHub Pages reads to keep
 * the custom domain attached (generated by src/pages/CNAME.ts).
 *
 * Include the protocol, no trailing slash — e.g. "https://chengwei.tw".
 *
 * TODO: still the placeholder. example.com is reserved by RFC 2606, so an
 * accidental deploy can't point at anyone's real domain — but GitHub Pages
 * will refuse to verify it, so this must be set before going live.
 * Nothing in development depends on it.
 */
const SITE = "https://example.com";

export default defineConfig({
  site: SITE,
  base: "/",
  trailingSlash: "always",
  integrations: [mdx(), sitemap()],
  build: {
    format: "directory",
  },
});
