import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";

/**
 * ▸ THE ONLY PLACE THE DOMAIN IS DEFINED. ◂
 *
 * Change this one line and everything follows: canonical URLs, Open Graph
 * tags, sitemap.xml, RSS links, and the CNAME file GitHub Pages reads to keep
 * the custom domain attached (generated by src/pages/CNAME.ts).
 *
 * Include the protocol, no trailing slash.
 *
 * This is the apex domain, not www — DNS must point wwwang.tw itself at
 * GitHub Pages (ALIAS/ANAME, or the four A records listed in the README).
 */
const SITE = "https://wwwang.tw";

export default defineConfig({
  site: SITE,
  base: "/",
  trailingSlash: "always",
  integrations: [mdx(), sitemap()],
  build: {
    format: "directory",
  },
});
